### ISSUE TITLE
rtbkit build error!

### ISSUE THREAD

**Issue by vincentami** [rtbkit/rtbkit#246]
ubunt 14.02 LTS

gcc 4.8.2;

boost:  1.57.0   , I download from the http://www.boost.org/  , replace the boost-svn , and install it ;

when i run make compile NODEJS_ENABLED=0,  there is always a error about link of boost like this:
" make compile NODEJS_ENABLED=0
           [BIN] classifier_training_tool
/home/vincent/rtbkit/build/x86_64/bin/libutils.so: undefined reference to `boost::iostreams::file_descriptor::seek(long long, std::_Ios_Seekdir)'
collect2: error: ld returned 1 exit status
make: *** [build/x86_64/bin/classifier_training_tool] Error 1
"
I check the boost library on  $home/local/, i think it is ok . Dose anyone meet this error ? Wish your help ,Thanks ~~

**Comment by mikeburkat** [comment]
Hi Vincent, you should not need to download boost 1.57 at all. All the dependencies are provided in our rtbkit-deps repo (https://github.com/rtbkit/rtbkit-deps). You should compile the dependencies repo first. Have you done that?

**Comment by arikin** [comment]
The boost 1.52 in the dependencies doesn't build on Ubuntu 14.04.2.
So vincentami is still correct.  I have only gotten the given version (1.52) to install on 14.04.5 which isn't available in AWS at least.
Specify the exact release version that the dependencies work on or update these frozen deps versions.

**Comment by mikeburkat** [comment]
Boost 1.57 is the version which should be used to build on ubuntu 14. You should be using rtbkit-deps instead of platform-deps. RTBkit deps is an updated, trimmed down version of platform-deps. You can find the instruction to build on ubuntu 14 here https://github.com/rtbkit/rtbkit/wiki/RTBkit-Deps-and-Ubuntu-14.04

**Comment by arikin** [comment]
mikeburkat.  Thank you. Confirmed that the rtbkit-deps install perfectly on the AWS Ubuntu 14.04.2 instance.

**Comment by modqhx** [comment]
Hi apologies for opening this again, I'm having same issues on ubuntu 14:

```
rtbkit@ip-172-31-1-006:~/rtbkit$ cp jml-build/sample.local.mk local.mk
rtbkit@ip-172-31-1-006:~/rtbkit$ make compile NODEJS_ENABLED=0
Must specify package names on the command line
Must specify package names on the command line
             [C] jml/utils/lz4cli.c
             [C] jml/utils/lz4.c
             [C] jml/utils/lz4hc.c
             [C] jml/utils/xxhash.c
           [C++] jml/arch/exception_hook.cc
           [C++] jml/arch/simd_vector.cc
           [C++] jml/arch/demangle.cc
In file included from ./jml/arch/demangle.cc:29:0:
./jml/utils/guard.h:25:30: fatal error: boost/function.hpp: No such file or directory
 #include <boost/function.hpp>
                              ^
compilation terminated.
make: *** [build/x86_64/obj/jml/arch/demangle.2b32dd864a54015d5909b18c616c48d9.lo] Error 1
```

**Comment by koushikmaratha** [comment]
Hi,

I also have the same issue on ubuntu 14.04

rtbkit@ip-172-31-39-48:~/rtbkit$ make compile  NODEJS_ENABLED=0
           [C++] jml/arch/demangle.cc
In file included from ./jml/arch/demangle.cc:29:0:
./jml/utils/guard.h:25:30: fatal error: boost/function.hpp: No such file or directory
 #include <boost/function.hpp>
                              ^
compilation terminated.
make: *** [build/x86_64/obj/jml/arch/demangle.79db72ee4fe1142b680367786fb6e93f.lo] Error 1

**Comment by Zaithe** [comment]
I'm having this same problem on Ubuntu 14.04 `root@derek-virtual-ubuntu:~/rtbkit# sudo make compile NODEJS_ENABLED=0
           [C++] jml/arch/demangle.cc
In file included from ./jml/arch/demangle.cc:29:0:
./jml/utils/guard.h:25:30: fatal error: boost/function.hpp: No such file or directory
 #include <boost/function.hpp>
                              ^
compilation terminated.
make: *** [build/x86_64/obj/jml/arch/demangle.1bd7239564c9612c89dbe7a628b3e831.lo] Error 1
`

**Comment by Zaithe** [comment]
I was able to get it running by executing sudo apt install libace-dev and then running for rtbkit-deps `sudo make all NODEJS_ENABLED=0`
